/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TILING_KEY_H_
#define QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

namespace optiling {
namespace QkvRmsNormRopeCacheWithKScale {

#ifndef QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128
#define QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128 128
#endif
#ifndef QKV_K_SCALE_ROPE_MODE_ROPE
#define QKV_K_SCALE_ROPE_MODE_ROPE 0
#endif
#ifndef QKV_K_SCALE_ROPE_MODE_MROPE
#define QKV_K_SCALE_ROPE_MODE_MROPE 1
#endif
#ifndef QKV_K_SCALE_K_QUANT_MODE_FP8
#define QKV_K_SCALE_K_QUANT_MODE_FP8 0
#endif
#ifndef QKV_K_SCALE_K_QUANT_MODE_INT8
#define QKV_K_SCALE_K_QUANT_MODE_INT8 1
#endif
#ifndef QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD
#define QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD 0
#endif
#ifndef QKV_K_SCALE_Q_QUANT_MODE_NO_QUANT
#define QKV_K_SCALE_Q_QUANT_MODE_NO_QUANT 1
#endif
#ifndef QKV_K_SCALE_LAYOUT_NTD
#define QKV_K_SCALE_LAYOUT_NTD 0
#endif
#ifndef QKV_K_SCALE_LAYOUT_TND
#define QKV_K_SCALE_LAYOUT_TND 1
#endif
#ifndef ASCENDC_TPL_4_BW
#define ASCENDC_TPL_4_BW 4
#endif

ASCENDC_TPL_ARGS_DECL(QkvRmsNormRopeCacheWithKScale,
                      ASCENDC_TPL_UINT_DECL(HEAD_DIM, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST,
                                            QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128),
                      ASCENDC_TPL_UINT_DECL(QKV_LAYOUT, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_NTD,
                                            QKV_K_SCALE_LAYOUT_TND),
                      ASCENDC_TPL_UINT_DECL(Q_OUT_LAYOUT, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_NTD,
                                            QKV_K_SCALE_LAYOUT_TND),
                      ASCENDC_TPL_UINT_DECL(ROPE_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                                            QKV_K_SCALE_ROPE_MODE_ROPE, QKV_K_SCALE_ROPE_MODE_MROPE),
                      ASCENDC_TPL_UINT_DECL(K_QUANT_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                                            QKV_K_SCALE_K_QUANT_MODE_FP8, QKV_K_SCALE_K_QUANT_MODE_INT8),
                      ASCENDC_TPL_UINT_DECL(Q_QUANT_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                                            QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD,
                                            QKV_K_SCALE_Q_QUANT_MODE_NO_QUANT));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(HEAD_DIM, ASCENDC_TPL_UI_LIST, QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128),
        ASCENDC_TPL_UINT_SEL(QKV_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_NTD),
        ASCENDC_TPL_UINT_SEL(Q_OUT_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_NTD),
        ASCENDC_TPL_UINT_SEL(ROPE_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_ROPE_MODE_ROPE),
        ASCENDC_TPL_UINT_SEL(K_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_K_QUANT_MODE_FP8),
        ASCENDC_TPL_UINT_SEL(Q_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(HEAD_DIM, ASCENDC_TPL_UI_LIST, QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128),
        ASCENDC_TPL_UINT_SEL(QKV_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_TND),
        ASCENDC_TPL_UINT_SEL(Q_OUT_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_NTD),
        ASCENDC_TPL_UINT_SEL(ROPE_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_ROPE_MODE_ROPE),
        ASCENDC_TPL_UINT_SEL(K_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_K_QUANT_MODE_FP8),
        ASCENDC_TPL_UINT_SEL(Q_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(HEAD_DIM, ASCENDC_TPL_UI_LIST, QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128),
        ASCENDC_TPL_UINT_SEL(QKV_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_TND),
        ASCENDC_TPL_UINT_SEL(Q_OUT_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_TND),
        ASCENDC_TPL_UINT_SEL(ROPE_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_ROPE_MODE_ROPE),
        ASCENDC_TPL_UINT_SEL(K_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_K_QUANT_MODE_FP8),
        ASCENDC_TPL_UINT_SEL(Q_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_Q_QUANT_MODE_PER_TOKEN_PER_HEAD)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(HEAD_DIM, ASCENDC_TPL_UI_LIST,
                                              QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TPL_HEAD_DIM_D128),
                         ASCENDC_TPL_UINT_SEL(QKV_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(Q_OUT_LAYOUT, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(ROPE_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_ROPE_MODE_MROPE),
                         ASCENDC_TPL_UINT_SEL(K_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_K_QUANT_MODE_INT8),
                         ASCENDC_TPL_UINT_SEL(Q_QUANT_MODE, ASCENDC_TPL_UI_LIST, QKV_K_SCALE_Q_QUANT_MODE_NO_QUANT)));

} // namespace QkvRmsNormRopeCacheWithKScale
} // namespace optiling

#endif // QKV_RMS_NORM_ROPE_CACHE_WITH_K_SCALE_TILING_KEY_H_
