#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ======================================================================================================================

####### 参数说明 ########
# head_dim=72 支持验证用例（2026-09）
# 覆盖: Dn(无mask config2)/Nd(有mask config2)/TND varlen/PA decode(FlashDecode, config3)/LSE/双精度/GQA
# PA_NZ + D=72 为已知不支持组合(NZ 分形粒度16不整除72), checker 显式拦截
# D=72 技术路线: 复用 D=128 config 模板, kernel 内 pad 到 Align64(72)=128, GM 搬出按真实 72 裁剪

# fmt: off

TestCases = {
    # ================================================================
    # Dn: 无 mask (config 2)
    # ================================================================
    "HD72_DN_BSND_S64": {
        "B": [2],
        "N1": [16],
        "N2": [16],
        "S1": [64],
        "S2": [128],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "layout_out": ["BSND"],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    "HD72_DN_BSND_S128": {
        "B": [2],
        "N1": [16],
        "N2": [16],
        "S1": [128],
        "S2": [256],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "layout_out": ["BSND"],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    "HD72_DN_BNSD_LSE": {
        "B": [2],
        "N1": [16],
        "N2": [16],
        "S1": [128],
        "S2": [256],
        "D": [72],
        "DV": [72],
        "Dtype": ["bf16"],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [True],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    "HD72_DN_TND_VARLEN": {
        "B": [3],
        "N1": [8],
        "N2": [8],
        "S1": [96],
        "S2": [200],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "layout_out": ["TND"],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "cu_seqlens_q": [[0, 32, 64, 96]],
        "cu_seqlens_kv": [[0, 70, 140, 200]],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    # GQA 分组比 4:1 (SigLIP 场景为 MHA, 此处验证 GQA 通用性)
    "HD72_DN_GQA_BSND": {
        "B": [2],
        "N1": [16],
        "N2": [4],
        "S1": [128],
        "S2": [256],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "layout_out": ["BSND"],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    # ================================================================
    # Nd: 有 mask (config 2)
    # ================================================================
    "HD72_ND_CAUSAL_BSND": {
        "B": [2],
        "N1": [16],
        "N2": [16],
        "S1": [128],
        "S2": [256],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "layout_out": ["BSND"],
        "mask_mode": [3],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    "HD72_ND_BAND_BNSD_LSE": {
        "B": [2],
        "N1": [16],
        "N2": [16],
        "S1": [128],
        "S2": [256],
        "D": [72],
        "DV": [72],
        "Dtype": ["bf16"],
        "layout_q": ["BNSD"],
        "layout_kv": ["BNSD"],
        "layout_out": ["BNSD"],
        "mask_mode": [4],
        "win_left": [64],
        "win_right": [64],
        "return_softmax_lse": [True],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    # ================================================================
    # PA decode: FlashDecode split-KV (config 2/3)
    # ================================================================
    "HD72_PA_BBND_DECODE": {
        "B": [8],
        "N1": [8],
        "N2": [1],
        "S1": [8],
        "S2": [1024],
        "D": [72],
        "DV": [72],
        "Dtype": ["fp16"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "layout_out": ["TND"],
        "cu_seqlens_q": [[0, 1, 2, 3, 4, 5, 6, 7, 8]],
        "seqused_q": [[1, 1, 1, 1, 1, 1, 1, 1]],
        "seqused_kv": [[1024, 900, 512, 300, 128, 100, 45, 1024]],
        "block_size": [128],
        "mask_mode": [3],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [True],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
    "HD72_PA_BNBD_DECODE": {
        "B": [4],
        "N1": [8],
        "N2": [2],
        "S1": [1],
        "S2": [768],
        "D": [72],
        "DV": [72],
        "Dtype": ["bf16"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BNBD"],
        "layout_out": ["BSND"],
        "seqused_kv": [[768, 500, 256, 60]],
        "block_size": [128],
        "mask_mode": [0],
        "win_left": [-1],
        "win_right": [-1],
        "return_softmax_lse": [False],
        "q_range": [(-5.0, 5.0)],
        "k_range": [(-5.0, 5.0)],
        "v_range": [(-5.0, 5.0)],
    },
}
