# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

from quant_flash_attn_paramset_common import expand_paramset_to_cases

TEST_PARAMS = {
    "TND_B1_QS4_KVS1024_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 4]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[4]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [4],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3_KVS640_Nq1_Nkv1_D64_SP0": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [64],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[3]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
    },
    "TND_B1_QS128_KVS2048_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 128]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[128]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [128],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS512_KVS5120_Nq80_Nkv2_D64_SP3": {
        "B": [1],
        "N_q": [80],
        "N_kv": [2],
        "D": [64],
        "cu_seqlens_q": [[0, 512]],
        "cu_seqlens_kv": [[0, 5120]],
        "seqused_q": [[512]],
        "seqused_kv": [[5120]],
        "max_seqlen_q": [512],
        "max_seqlen_kv": [5120],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS10_KVS128_Nq2_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [2],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 10]],
        "cu_seqlens_kv": [[0, 128]],
        "seqused_q": [[10]],
        "seqused_kv": [[128]],
        "max_seqlen_q": [10],
        "max_seqlen_kv": [128],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS699_KVS777_Nq64_Nkv2_D128_SP0": {
        "B": [1],
        "N_q": [64],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 699]],
        "cu_seqlens_kv": [[0, 777]],
        "seqused_q": [[699]],
        "seqused_kv": [[777]],
        "max_seqlen_q": [699],
        "max_seqlen_kv": [777],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS1_KVS1100_Nq32_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [32],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_kv": [[0, 1100]],
        "seqused_q": [[1]],
        "seqused_kv": [[1100]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [1100],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3000_KVS6000_Nq16_Nkv8_D64_SP3": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [64],
        "cu_seqlens_q": [[0, 3000]],
        "cu_seqlens_kv": [[0, 6000]],
        "seqused_q": [[3000]],
        "seqused_kv": [[6000]],
        "max_seqlen_q": [3000],
        "max_seqlen_kv": [6000],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS768_KVS5504_Nq56_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [56],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 768]],
        "cu_seqlens_kv": [[0, 5504]],
        "seqused_q": [[768]],
        "seqused_kv": [[5504]],
        "max_seqlen_q": [768],
        "max_seqlen_kv": [5504],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
    },
    "TND_B1_QS2_KVS640_Nq56_Nkv4_D128_SP0": {
        "B": [1],
        "N_q": [56],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 2]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[2]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [2],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [256.0],
        "enable_lse": [False],
    },
    "TND_B3_QS1_KVS999_Nq256_Nkv4_D64_SP3": {
        "B": [3],
        "N_q": [256],
        "N_kv": [4],
        "D": [64],
        "cu_seqlens_q": [[0, 1, 2, 4]],
        "cu_seqlens_kv": [[0, 999, 2215, 3047]],
        "seqused_q": [[1, 1, 2]],
        "seqused_kv": [[999, 1216, 832]],
        "max_seqlen_q": [2],
        "max_seqlen_kv": [1216],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS600_KVS500_Nq16_Nkv8_D128_SP0": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 600]],
        "cu_seqlens_kv": [[0, 500]],
        "seqused_q": [[600]],
        "seqused_kv": [[500]],
        "max_seqlen_q": [600],
        "max_seqlen_kv": [500],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B2_QS900_KVS1500_Nq96_Nkv16_D128_SP3": {
        "B": [2],
        "N_q": [96],
        "N_kv": [16],
        "D": [128],
        "cu_seqlens_q": [[0, 900, 1966]],
        "cu_seqlens_kv": [[0, 1500, 3427]],
        "seqused_q": [[900, 1066]],
        "seqused_kv": [[1500, 1927]],
        "max_seqlen_q": [1066],
        "max_seqlen_kv": [1927],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [128.0],
        "enable_lse": [False],
    },
    "TND_B1_QS2000_KVS320_Nq4_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [4],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 2000]],
        "cu_seqlens_kv": [[0, 320]],
        "seqused_q": [[2000]],
        "seqused_kv": [[320]],
        "max_seqlen_q": [2000],
        "max_seqlen_kv": [320],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3_KVS768_Nq16_Nkv1_D64_SP3": {
        "B": [1],
        "N_q": [16],
        "N_kv": [1],
        "D": [64],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 768]],
        "seqused_q": [[3]],
        "seqused_kv": [[768]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [768],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS4032_KVS2048_Nq8_Nkv8_D128_SP3": {
        "B": [1],
        "N_q": [8],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 4032]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[4032]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [4032],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [256.0],
        "enable_lse": [False],
    },
}

CASES = expand_paramset_to_cases(TEST_PARAMS)
SKIP_CASES = set()
