/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef FLASH_ATTN_GRAD_PROTO_H
#define FLASH_ATTN_GRAD_PROTO_H

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
* @brief Function FlashAttnGrad: the backward gradient computation of Flash Attention.
* Given the forward intermediate results (attn_out and softmax_lse) and the output
* gradient dout, computes the gradients of q, k and v. The metadata generated by
* FlashAttnMetadata with is_grad_enabled=true is required for task partitioning.

* @par Inputs:
* Thirteen inputs, including:
* @li q: A tensor. Type is float16, bfloat16. The query tensor.
* @li k: A tensor. Type is float16, bfloat16. The key tensor.
* @li v: A tensor. Type is float16, bfloat16. The value tensor.
* @li dout: A tensor. Type is float16, bfloat16. The gradient of attention output.
* @li attn_out: A tensor. Type is float16, bfloat16. The attention output of forward pass.
* @li softmax_lse: A tensor. Type is float32. The softmax LSE of forward pass.
* @li cu_seqlens_q: An optional tensor. Type is int32. The cumulative sequence lengths of
* query, required when layout_q is TND.
* @li cu_seqlens_kv: An optional tensor. Type is int32. The cumulative sequence lengths of
* key and value, required when layout_kv is TND.
* @li seqused_q: An optional tensor. Type is int32. The actual used query sequence lengths.
* @li seqused_kv: An optional tensor. Type is int32. The actual used key and value sequence lengths.
* @li sinks: An optional tensor. Type is float32. The sink tensor.
* @li attn_mask: An optional tensor. Type is int8. The attention mask, used when mask_mode is 3 or 4.
* @li metadata: An optional tensor. Type is int32. The task partition metadata generated by
* FlashAttnMetadata with is_grad_enabled=true, required in actual invocation.

* @par Outputs:
* Three outputs, including:
* @li dq: A tensor. Type is float16, bfloat16. The gradient of query.
* @li dk: A tensor. Type is float16, bfloat16. The gradient of key.
* @li dv: A tensor. Type is float16, bfloat16. The gradient of value.

* @par Attributes:
* Nine attributes, including:
* @li softmax_scale: A float. The softmax scale factor, 0.0 means 1/sqrt(D).
* @li mask_mode: An int. The mask mode, 0 means no mask, 3 means causal mask, 4 means window mask.
* @li win_left: An int. The left window size of window mask, valid when mask_mode is 4.
* @li win_right: An int. The right window size of window mask, valid when mask_mode is 4.
* @li max_seqlen_q: An int. The max sequence length of query, -1 means unset.
* @li max_seqlen_kv: An int. The max sequence length of key and value, -1 means unset.
* @li layout_q: A string. The layout of query, default is "BSND".
* @li layout_kv: A string. The layout of key and value, default is "BSND".
* @li layout_out: A string. The layout of output, default is "BSND".
*/
REG_OP(FlashAttnGrad)
    .INPUT(q, TensorType({DT_FLOAT16, DT_BF16}))
    .INPUT(k, TensorType({DT_FLOAT16, DT_BF16}))
    .INPUT(v, TensorType({DT_FLOAT16, DT_BF16}))
    .INPUT(dout, TensorType({DT_FLOAT16, DT_BF16}))
    .INPUT(attn_out, TensorType({DT_FLOAT16, DT_BF16}))
    .INPUT(softmax_lse, TensorType({DT_FLOAT}))
    .OPTIONAL_INPUT(cu_seqlens_q, TensorType({DT_INT32}))
    .OPTIONAL_INPUT(cu_seqlens_kv, TensorType({DT_INT32}))
    .OPTIONAL_INPUT(seqused_q, TensorType({DT_INT32}))
    .OPTIONAL_INPUT(seqused_kv, TensorType({DT_INT32}))
    .OPTIONAL_INPUT(sinks, TensorType({DT_FLOAT}))
    .OPTIONAL_INPUT(attn_mask, TensorType({DT_INT8}))
    .OPTIONAL_INPUT(metadata, TensorType({DT_INT32}))
    .OUTPUT(dq, TensorType({DT_FLOAT16, DT_BF16}))
    .OUTPUT(dk, TensorType({DT_FLOAT16, DT_BF16}))
    .OUTPUT(dv, TensorType({DT_FLOAT16, DT_BF16}))
    .ATTR(softmax_scale, Float, 0.0)
    .ATTR(mask_mode, Int, 0)
    .ATTR(win_left, Int, -1)
    .ATTR(win_right, Int, -1)
    .ATTR(max_seqlen_q, Int, -1)
    .ATTR(max_seqlen_kv, Int, -1)
    .ATTR(layout_q, String, "BSND")
    .ATTR(layout_kv, String, "BSND")
    .ATTR(layout_out, String, "BSND")
    .OP_END_FACTORY_REG(FlashAttnGrad)

} // namespace ge

#endif // FLASH_ATTN_GRAD_PROTO_H
