/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file mega_moe_tiling_key.h
 * \brief
 */

#ifndef MEGA_MOE_TILING_KEY_H
#define MEGA_MOE_TILING_KEY_H
#include "ascendc/host_api/tiling/template_argument.h"

namespace Mc2Tiling {
#define DISPATCH_QUANT_MODE_MXFP 4
#define EXPERT_QUANT_OUT_DTYPE_E5M2 3
#define EXPERT_QUANT_OUT_DTYPE_E4M3FN 4
#define EXPERT_QUANT_OUT_DTYPE_E2M1 5
#define COMBINE_QUANT_OUT_TYPE_NO_QUANT 0
#define COMBINE_QUANT_OUT_TYPE_E5M2 3
#define COMBINE_QUANT_OUT_TYPE_E4M3FN 4
#define TILINGKEY_TPL_MTE 0
#define TILINGKEY_TPL_URMA 1
#define TOPK_WEIGHTS_TYPE_DISABLED 0
#define TOPK_WEIGHTS_TYPE_ENABLED 1
#define MOE_WEIGHT1_INPUT_INDEX 4
#define SHARED_WEIGHT1_INPUT_INDEX 12

ASCENDC_TPL_ARGS_DECL(
    MegaMoe,
    ASCENDC_TPL_DATATYPE_DECL(TILINGKEY_MOE_WEIGHT_DTYPE, C_DT_FLOAT8_E5M2, C_DT_FLOAT8_E4M3FN, C_DT_FLOAT4_E2M1,
                              ASCENDC_TPL_INPUT(MOE_WEIGHT1_INPUT_INDEX)),
    ASCENDC_TPL_DATATYPE_DECL(TILINGKEY_SHARED_WEIGHT_DTYPE, C_DT_FLOAT8_E5M2, C_DT_FLOAT8_E4M3FN, C_DT_FLOAT4_E2M1,
                              ASCENDC_TPL_INPUT(SHARED_WEIGHT1_INPUT_INDEX)),
    ASCENDC_TPL_UINT_DECL(TILINGKEY_DISPATCH_QUANT_MODE, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST,
                          DISPATCH_QUANT_MODE_MXFP),
    ASCENDC_TPL_UINT_DECL(TILINGKEY_DISPATCH_QUANT_OUT_DTYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                          EXPERT_QUANT_OUT_DTYPE_E5M2, EXPERT_QUANT_OUT_DTYPE_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E2M1),
    ASCENDC_TPL_UINT_DECL(TILINGKEY_SHARED_QUANT_OUT_DTYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                          EXPERT_QUANT_OUT_DTYPE_E5M2, EXPERT_QUANT_OUT_DTYPE_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E2M1),
    ASCENDC_TPL_UINT_DECL(TILINGKEY_COMBINE_QUANT_OUT_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                          COMBINE_QUANT_OUT_TYPE_NO_QUANT, COMBINE_QUANT_OUT_TYPE_E5M2, COMBINE_QUANT_OUT_TYPE_E4M3FN),
    ASCENDC_TPL_UINT_DECL(TILINGKEY_COMM_MODE, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_MTE,
                          TILINGKEY_TPL_URMA),
    ASCENDC_TPL_BOOL_DECL(TILINGKEY_TOPK_WEIGHTS_TYPE, TOPK_WEIGHTS_TYPE_DISABLED, TOPK_WEIGHTS_TYPE_ENABLED), );

#define MEGA_MOE_TPL_CONFIG(MOE_WEIGHT_DTYPE, MOE_QUANT_DTYPE, SHARED_WEIGHT_DTYPE, SHARED_QUANT_DTYPE, COMM_MODE) \
    ASCENDC_TPL_ARGS_SEL( \
        ASCENDC_TPL_DATATYPE_SEL(TILINGKEY_MOE_WEIGHT_DTYPE, MOE_WEIGHT_DTYPE), \
        ASCENDC_TPL_DATATYPE_SEL(TILINGKEY_SHARED_WEIGHT_DTYPE, SHARED_WEIGHT_DTYPE), \
        ASCENDC_TPL_UINT_SEL(TILINGKEY_DISPATCH_QUANT_MODE, ASCENDC_TPL_UI_LIST, DISPATCH_QUANT_MODE_MXFP), \
        ASCENDC_TPL_UINT_SEL(TILINGKEY_DISPATCH_QUANT_OUT_DTYPE, ASCENDC_TPL_UI_LIST, MOE_QUANT_DTYPE), \
        ASCENDC_TPL_UINT_SEL(TILINGKEY_SHARED_QUANT_OUT_DTYPE, ASCENDC_TPL_UI_LIST, SHARED_QUANT_DTYPE), \
        ASCENDC_TPL_UINT_SEL(TILINGKEY_COMBINE_QUANT_OUT_TYPE, ASCENDC_TPL_UI_LIST, COMBINE_QUANT_OUT_TYPE_NO_QUANT, \
                             COMBINE_QUANT_OUT_TYPE_E5M2, COMBINE_QUANT_OUT_TYPE_E4M3FN), \
        ASCENDC_TPL_UINT_SEL(TILINGKEY_COMM_MODE, ASCENDC_TPL_UI_LIST, COMM_MODE), \
        ASCENDC_TPL_BOOL_SEL(TILINGKEY_TOPK_WEIGHTS_TYPE, TOPK_WEIGHTS_TYPE_DISABLED, TOPK_WEIGHTS_TYPE_ENABLED), \
        ASCENDC_TPL_TILING_STRUCT_SEL(MegaMoeTilingData))

// MTE 支持 MoE/shared 四种量化配置的任意组合。
ASCENDC_TPL_SEL(MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E5M2, EXPERT_QUANT_OUT_DTYPE_E5M2, C_DT_FLOAT8_E5M2,
                                    EXPERT_QUANT_OUT_DTYPE_E5M2, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E5M2, EXPERT_QUANT_OUT_DTYPE_E5M2, C_DT_FLOAT8_E4M3FN,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E5M2, EXPERT_QUANT_OUT_DTYPE_E5M2, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E5M2, EXPERT_QUANT_OUT_DTYPE_E5M2, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E2M1, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT8_E5M2,
                                    EXPERT_QUANT_OUT_DTYPE_E5M2, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT8_E4M3FN,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E2M1, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT8_E5M2,
                                    EXPERT_QUANT_OUT_DTYPE_E5M2, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT8_E4M3FN,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E2M1, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E2M1, C_DT_FLOAT8_E5M2,
                                    EXPERT_QUANT_OUT_DTYPE_E5M2, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E2M1, C_DT_FLOAT8_E4M3FN,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E2M1, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_MTE),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E2M1, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E2M1, TILINGKEY_TPL_MTE),

                // URMA 保持 MoE/shared 量化配置一致的现有约束。
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E5M2, EXPERT_QUANT_OUT_DTYPE_E5M2, C_DT_FLOAT8_E5M2,
                                    EXPERT_QUANT_OUT_DTYPE_E5M2, TILINGKEY_TPL_URMA),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT8_E4M3FN, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT8_E4M3FN,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_URMA),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E4M3FN, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E4M3FN, TILINGKEY_TPL_URMA),
                MEGA_MOE_TPL_CONFIG(C_DT_FLOAT4_E2M1, EXPERT_QUANT_OUT_DTYPE_E2M1, C_DT_FLOAT4_E2M1,
                                    EXPERT_QUANT_OUT_DTYPE_E2M1, TILINGKEY_TPL_URMA));

#undef MEGA_MOE_TPL_CONFIG
#undef SHARED_WEIGHT1_INPUT_INDEX
#undef MOE_WEIGHT1_INPUT_INDEX
} // namespace Mc2Tiling
#endif
